[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/auth/*"
  to = "https://TU_BACKEND/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/twitch/*"
  to = "https://TU_BACKEND/twitch/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/channel/*"
  to = "https://TU_BACKEND/channel/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200